# -*- coding: utf-8 -*-
"""Streamlitipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19K_GMySSIKrOTbxMvP4YdWae7TewHhVu
"""

try:
  import streamlit as st
  except ModuleNotFoundError:
    import os
    os.system("pip install streamlit")
    import streamlit as st

import pandas as pd
import plotly.express as px

df=pd.read_csv('/content/Advertising_F.csv')

st.title("Advertising Effectiveness Dashboard_Clay")
st.sidebar{"Header"}
x_var=st.sidebar.selectbox("X-Axis",['TV','Radio','Newspaper'])
y_var=st.sidebar.selectbox("Y-Axis",['sales'])

fig=px.scatter(df,x=x_var,y=y_var,trendline="ols")
st.plotly_chart(fig)

#lets show a map
st.title( "I'm the mmap ")
fig=px.scatter_mapbox(df,lat="Latitude",lon="Longitude",color='sales',
                      size='TV',hover_name='City')
fig.update_layout(mapbox_=style"carto-poositron")
st.plotly_chart_(fig)